---
title: dictionary creation
output:
  html_document:
    toc: true
runtime: shiny
---

<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{dictionary creation}
-->

```{r, echo = FALSE, message = FALSE}
library(knitr)
library(datadict)
opts_chunk$set(comment = "#>", error = FALSE, tidy = FALSE)
opts_chunk$set(fig.width = 3.5, fig.height = 2.5, dpi = 100)
```

```{r}
library(dplyr) 
```

```{r}
iris_dict <- data.frame() %>%
  add_dict_entries(iris, "Sepal.Length", 
    units = "cm", name_long = "sepal length", description = "length of the sepal") %>%
  add_dict_entries(iris, "Sepal.Width", 
    units = "cm", name_long = "sepal width", description = "width of the sepal") %>%
  add_dict_entries(iris, "Petal.Length", 
    units = "cm", name_long = "petal length", description = "length of the petal") %>%
  add_dict_entries(iris, "Petal.Width", 
    units = "cm", name_long = "petal width", description = "width of the petal") %>%
  add_dict_entries(iris, "Species",
    units = NA, name_long = "species", description = "species of the flower") 
```